name: Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: devlopesbernardo/hello-world-go:${{ steps.vars.outputs.sha_short }}
          
      - name: Checkout the other repository
        uses: actions/checkout@v2
        with:
          repository: 'bernardolsp/aulao-pipeline' # replace with your repository
          token: ${{ secrets.PAT }} # use the PAT you saved as a secret
          path: 'aulao-pipeline' # this is the directory where the other repo will be checked out

      - name: Run sed on the other repository
        run: |
          cd aulao-pipeline
          touch test.txt

      - name: Commit and push changes
        run: |
          cd other-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Commit message" # replace with your commit message
          git push
